# Generated by Django 2.1.7 on 2019-03-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20190310_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=140, null=True),
        ),
    ]
