# Generated by Django 2.1.7 on 2019-03-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20190311_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='timeline.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AlterField(
            model_name='follow',
            name='followers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='timeline.Profile'),
        ),
    ]
