# Generated by Django 2.1.7 on 2019-03-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20190310_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='timeline.Profile'),
        ),
    ]
